sudo: false
language: node_js
node_js:
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'
script: ./production.sh
deploy:
  local_dir: $PUBLICFOLDER
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master